name: Qodana

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

  qodana:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Qodana Scan
      uses: JetBrains/qodana-action@v2023.2
      env:
        QODANA_TOKEN: ${{ secrets.SECRET_NAME }}   
            
        
